### ISSUE TITLE
Error after read QR code

### ISSUE THREAD

**Issue by watzapnet** [mtaupiq/wa-chatgpt#2]
TypeError: chatgpt.initSession is not a function
    at main (file:///C:/Users/Antique/wa-chatgpt/index.js:51:17)
    at Client.<anonymous> (file:///C:/Users/Antique/wa-chatgpt/index.js:32:3)
    at Client.emit (node:events:513:28)
    at Client.initialize (C:\Users\Antique\wa-chatgpt\node_modules\whatsapp-web.js\src\Client.js:551:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Any help would be appreciated.

**Comment by dudegladiator** [comment]
Open AI is increasing their security of accessing unofficial API day by day .
Due to this all this type error are coming .
